IMAGE_FOLDER_PATH='./assets/images'
IMAGE_DEFAULT_PATH= f'{IMAGE_FOLDER_PATH}/image_default2.jpg'

FONT_FOLDER_PATH='./assets/fonts'
FONT_POPPINS_LIGHT_PATH=f'{FONT_FOLDER_PATH}/poppins_light.ttf'
FONT_POPPINS_REGULAR_PATH=f'{FONT_FOLDER_PATH}/poppins_regular.ttf'
FONT_POPPINS_MEDIUM_PATH=f'{FONT_FOLDER_PATH}/poppins_medium.ttf'
FONT_POPPINS_BOLD_PATH=f'{FONT_FOLDER_PATH}/poppins_bold.ttf'

FONT_PRO_LIGHT_PATH=f'{FONT_FOLDER_PATH}/pro_light.ttf'

JSON_FOLDER_PATH='./assets/jsons'

THEME_PATH=f'{JSON_FOLDER_PATH}/theme.json'

SOLUTION_FOLDER_PATH=f'{JSON_FOLDER_PATH}/solutions'
SOLUTION_DEFAULT_PATH=f'{SOLUTION_FOLDER_PATH}/solution_default.json'

NODES_BASE_INFO_PATH=f'{JSON_FOLDER_PATH}/nodes_base_info.json'
NODES_FILTERING_INFO_PATH=f'{JSON_FOLDER_PATH}/nodes_filtering_info.json'
NODES_MORPHOLOGY_INFO_PATH=f'{JSON_FOLDER_PATH}/nodes_morphology_info.json'
NODES_SPECIAL_INFO_PATH=f'{JSON_FOLDER_PATH}/nodes_special_info.json'
